name: attendanceapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.8
  geolocator: ^13.0.2
  get: ^4.6.6
  google_maps_flutter: ^2.10.0
  intl: ^0.19.0
  sqflite: ^2.4.1
  path: ^1.9.0
  path_provider: ^2.1.5 # Useful for DB path

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
